name = "metafikra-mindmap-ai"
main = "worker.js"
compatibility_date = "2024-09-23"

routes = [
  { pattern = "metafikra.com/api/*", zone_name = "metafikra.com" },
  { pattern = "www.metafikra.com/api/*", zone_name = "metafikra.com" }
]

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "metafikra_mindmap_jwt_secret_key_2026"

[[d1_databases]]
binding = "DB"
database_name = "metafikra-db"
database_id = "e20b926a-b69a-4e9e-94e7-5d5f4e5d78d2"
